### ISSUE TITLE
SMS check

### ISSUE THREAD

**Issue by joaocarlossm** [victordaga/MadnessBot#1]
Como você conseguiu passar pela dupla verificação do sms?
Achei que você era estrangeiro até ver no código, "Erro geral mané" kkkkkkkkk muito bom

**Comment by ovictordaga** [comment]
Oi João, tudo bom?
Então hahaha esse codigo na realidade foi uma versão beta de outro código. 
Hoje o bot está um pouco mais avançado mas infelizmente estou sem tempo e acabei pausando o projeto por um tempo. 

Você provavelmente vai encontrar dois problemas principais na loja SNKRS Brasil:
**-Ban de IP
-SMS 
-reCaptcha**

Vc pode ter duas abordagens principais com cada uma, ter um sistema próprio que resolva isso ou então contratar um serviço com API que resolva seu problema. 

Eu recomendo altamente que vc contrate um serviço bom pois tem uns bem baratos que podem ser uteis. 
-**Ban de IP:** Recomendo contratar um bom Proxy ou VPN, de preferencia um que randomize ou permita que vc de x em x tempo mude o ip que vc está usando como intermediário. Eu utilizei e gostei do: https://btwproxy.io/ mas o https://smartproxy.com/?x-clickref=1100livqHaGT também é uma boa.

-**SMS:** Nesse caso vc precisa de um sistema confiavel que permita vc criar numeros online e uma caixa de sms virtual com uma api pra vc bater e receber os dados. Gostei do  https://www.vonage.com/ e do https://www.twilio.com/pt-br/messaging

-Para o **reCaptcha** sempre é uma corrida, pois eles podem mudar a cada versão, mas normalmente os sistemas "turco mecanico" funcionam bem e são rapidos. Não cheguei a ter tanto contato mas recomendo o https://2captcha.com/ e o que mais conheci foi o https://www.deathbycaptcha.com/

Existe tambem um problema com a versão  do Cromium que se usa, algumas estavam dando conflito.

Espero que funcione, e qualquer coisa é só mandar por aqui.

**Comment by ovictordaga** [comment]
Olá João, eu agradeço o contato e a proposta, mas infelizmente hoje fica complicado.
Entretanto tem uma galera mandando MUITO bem no brasil que é a galera da Rocket.
Eles vendem slots pro bot deles direto, recomendo fortemente.

https://www.instagram.com/rocketautomatic/

Abraços,
